### ISSUE TITLE
Linking gives error with genRand

### ISSUE THREAD

**Issue by FlexingJem** [ESultanik/mtwister#5]
I was using this rand library for a project, so I tried using it, but my linker gives the error "undefined reference to `genrand'".
Here's the full error:
```
    /usr/bin/ld: /tmp/ccqZknr1.o: in function `main':
    game.c:(.text+0x2e): undefined reference to `seedRand'
    /usr/bin/ld: game.c:(.text+0x49): undefined reference to `genRand'
    collect2: error: ld returned 1 exit status
```
Help would definitely appreciated. For the code that caused this, it's literally the exact same code from the repo, with the same test code.

**Comment by wallabra** [comment]
`genRand` is defined in `mtwister.c`. Are you not linking the library properly?

**Comment by FlexingJem** [comment]
I'm using the exact code from the repository. The linked code is the same as in the README.md file. I don't know what's wrong, I think it's just an annoying bug with GCC. I'll try it with MSVC.

**Comment by wallabra** [comment]
There's no reason the linker shouldn't be finding the function, provided that you are compiling `mtwister.c` and linking it in with your own objects. But I can't know if your setup is correct without seeing your Makefile or Meson.build or whatever you're using to setup compilation.

**Comment by FlexingJem** [comment]
I'm only using WSL and the command "gcc game.c -o game". I don't know why it's not working, nor do I have the brain power to figure it out.
Here's the LS of the directory, and the error from my WSL terminal.
![Screenshot 2024-07-18 193243](https://github.com/user-attachments/assets/4f1c5ef6-b3cf-4387-b56c-80c44cba7a7b)

**Comment by wallabra** [comment]
> I'm only using WSL and the command "gcc game.c -o game"

That's the issue. You have to pass `game.c mtwister.c`. Or better yet, compile each C file into its objects, then link them together:

```sh
gcc game.c -c -o game.o
gcc mtwister.c -c -o mtwister.o
gcc game.o mtwister.o -o game
```

Usually you can set up a build system to do that for you.

I suggest you take a refresher on how C linking works, but I'm always here to help  :)

**Comment by FlexingJem** [comment]
Thanks! I'm new to C, and I just needed some help.
